"""Build the feature matrix (feature-matrix.md) from the research passes.

Inputs, all in this folder unless given on the command line:
- first-pass-sources.json: the 2026-10-02 first pass, keys assigned from the ideas note
- ../sources/*.md: research reports with a table that has a "feature keys" column
- status.json: our status per feature key (have / 1.0 / 1.x / rejected), with the
  satellite package, size cost, whether it changes seeds, and a reason

Run: python build_matrix.py
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent


def parse_tables(path):
    """Rows of every markdown table that has a column whose header mentions 'feature keys'."""
    rows = []
    lines = path.read_text(encoding="utf-8").splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|\s*:?-{3,}", lines[i + 1]):
            header = [h.strip().lower() for h in line.strip().strip("|").split("|")]
            key_col = next((k for k, h in enumerate(header) if "feature key" in h), None)
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                if key_col is not None and len(cells) > key_col:
                    name = re.sub(r"\*\*|\[|\]\([^)]*\)", "", cells[0]).strip()
                    kind = cells[1] if len(cells) > 1 else ""
                    url = next((c for c in cells if c.startswith("http")), "")
                    m = re.search(r"https?://\S+", " ".join(cells))
                    if not url and m:
                        url = m.group(0).rstrip(";,)")
                    keys = [k.strip().split(" ")[0].strip("`") for k in cells[key_col].split(",") if k.strip()]
                    keys = [k for k in keys if re.match(r"^[a-z][a-z0-9-]+$", k) and k not in ("no", "yes")]
                    rows.append({"name": name, "kind": kind, "url": url, "keys": keys, "from": path.name})
                i += 1
            continue
        i += 1
    return rows


def main():
    sources = json.loads((HERE / "first-pass-sources.json").read_text(encoding="utf-8"))
    for s in sources:
        s["from"] = "first pass"
    for p in sorted((HERE.parent / "sources").glob("*.md")):
        sources.extend(parse_tables(p))
    status = json.loads((HERE / "status.json").read_text(encoding="utf-8"))

    have = {}
    for s in sources:
        for k in s["keys"]:
            have.setdefault(k, []).append(s["name"])

    missing = sorted(k for k in have if k not in status)
    unused = sorted(k for k in status if k not in have)
    if missing:
        print("keys with no status (add them to status.json):", ", ".join(missing))

    out = []
    out.append("---")
    out.append('title: "Feature matrix: every feature found in any surveyed generator, who has it, and our status"')
    out.append("kind: note")
    out.append("status: active")
    out.append("date: 2026-10-02")
    out.append("verified: 2026-10-02")
    out.append("stale_after: 2027-04-02")
    out.append("tags: [galaxy-kb, feature-matrix, competition, stage-1]")
    out.append('summary: "read when deciding what the generator must do to out-do every other one: one row per feature found anywhere, the generators that have it, and our status (have, 1.0, 1.x or rejected with a reason), size cost and package; generated by build_matrix.py, never edited by hand"')
    out.append("---")
    out.append("")
    out.append("# Feature matrix")
    out.append("")
    out.append(f"Generated by `build_matrix.py` from {len(sources)} sources and {len(have)} features (plus {len(unused)} features of our own that no surveyed generator has). Do not edit by hand: change `status.json` or the source reports and run the script.")
    out.append("")
    out.append("Status: **have** = the game's generator does it today; **1.0** = in the first release; **1.x** = later, additive, no seed change; **rejected** = with the reason. Seeds: **yes** means adding it later would change what existing seeds produce, so it must be in 1.0 or behind a new generator version. Package: where the code or data lives under the D19 size budget (core = `UniverseGenerator`). Size: estimated added compressed size.")
    out.append("")
    groups = {}
    for k, st in status.items():
        groups.setdefault(st.get("group", "Other"), []).append(k)
    counts = {}
    for st in status.values():
        counts[st["status"]] = counts.get(st["status"], 0) + 1
    out.append("Totals: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())) + ".")
    out.append("")
    for group, keys in groups.items():
        out.append(f"## {group}")
        out.append("")
        out.append("| Feature | What it means | Who has it | Count | Our status | Seeds | Package | Size | Why |")
        out.append("|---|---|---|---|---|---|---|---|---|")
        for k in keys:
            st = status[k]
            who = have.get(k, [])
            shown = ", ".join(sorted(set(who))[:12]) + (f" and {len(set(who)) - 12} more" if len(set(who)) > 12 else "")
            out.append(f"| `{k}` | {st.get('means', '')} | {shown or '(none found)'} | {len(set(who))} | {st['status']} | {st.get('seeds', '')} | {st.get('package', '')} | {st.get('size', '')} | {st.get('why', '')} |")
        out.append("")
    out.append("## Sources")
    out.append("")
    out.append("| Source | Kind | From | Features |")
    out.append("|---|---|---|---|")
    for s in sorted(sources, key=lambda s: s["name"].lower()):
        link = f"[{s['name']}]({s['url']})" if s.get("url") else s["name"]
        out.append(f"| {link} | {s.get('kind', '')} | {s['from']} | {len(s['keys'])} |")
    out.append("")
    out.append("Related: [status.json](status.json), [../INDEX.md](../INDEX.md).")
    (HERE / "feature-matrix.md").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote feature-matrix.md: {len(sources)} sources, {len(have)} features found, {len(status)} with status")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
