#!/usr/bin/env python3
"""Write Runtime/Names/StarTables.cs from RandomNameGeneratorLibrary's three star resources (plan D20).

    python scripts/embed-star-tables.py <folder holding Resources.stars.*.stripped>

The tables become C# string constants, so the same bytes compile for NuGet and in Unity, with no resource loader, no
TextAsset and nothing parsed in a static constructor (they are split on first use). Re-running on the same input
writes the same file. The output changes generated names: before the first release that is a deliberate golden
rewrite; after it, a new generator version.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "Packages" / "com.m4bwav.universe-generator" / "Runtime" / "Names" / "StarTables.cs"
WIDTH = 110


def read_lines(folder: pathlib.Path, name: str) -> list[str]:
    text = (folder / f"Resources.stars.{name}.stripped").read_bytes().decode("utf-8")
    return [line.strip() for line in text.replace("\r\n", "\n").split("\n") if line.strip()]


def literal(items: list[str], separator: str, indent: str) -> str:
    for item in items:
        if separator in item or '"' in item or "\\" in item:
            raise SystemExit(f"cannot embed {item!r}")
    chunks, line = [], ""
    for item in items:
        piece = item + separator
        if line and len(line) + len(piece) > WIDTH:
            chunks.append(line)
            line = ""
        line += piece
    chunks.append(line.rstrip(separator))
    return f"\n{indent}+ ".join(f'"{c}"' for c in chunks)


def main() -> None:
    folder = pathlib.Path(sys.argv[1])
    proper = read_lines(folder, "proper")
    designations = read_lines(folder, "designations")
    gaps = read_lines(folder, "hipgaps")
    highest, gap_numbers = int(gaps[0]), [int(g) for g in gaps[1:]]
    if gap_numbers != sorted(gap_numbers) or gap_numbers[-1] >= highest:
        raise SystemExit("Hipparcos gaps must be ascending and below the highest number")

    indent = " " * 12
    text = f"""// <auto-generated>
// Written by scripts/embed-star-tables.py from RandomNameGeneratorLibrary 2.2.0's star resources (plan D20); do not edit.
// RandomNameGeneratorLibrary: Copyright (c) 2014-2026 Mark Rogers, MIT licence, https://github.com/m4bwav/DotNetRandomNameGenerator
// Data: IAU Catalog of Star Names (IAU Working Group on Star Names); Bayer and Flamsteed names from the Yale Bright Star
// Catalogue, 5th ed. (Hoffleit and Warren 1991, VizieR V/50); Hipparcos catalogue numbers (ESA 1997, VizieR I/239).
// </auto-generated>
#nullable enable
namespace UniverseGeneration
{{
    internal static class StarTables
    {{
        /// <summary>The {len(proper)} IAU proper star names, separated by '|'.</summary>
        public const string Proper =
            {literal(proper, "|", indent)};

        /// <summary>The {len(designations)} Bayer and Flamsteed designations of the Yale Bright Star Catalogue, separated by '|'.</summary>
        public const string Designations =
            {literal(designations, "|", indent)};

        /// <summary>The highest Hipparcos number.</summary>
        public const int HipparcosHighest = {highest};

        /// <summary>The {len(gap_numbers)} numbers below <see cref="HipparcosHighest"/> that the Hipparcos catalogue skips, ascending, separated by ','.</summary>
        public const string HipparcosGaps =
            {literal([str(g) for g in gap_numbers], ",", indent)};
    }}
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}: {len(proper)} proper, {len(designations)} designations, "
          f"{len(gap_numbers)} Hipparcos gaps, {len(text.encode('utf-8')):,} bytes")


if __name__ == "__main__":
    main()
