"""Generate Runtime/Core/JsonExport.cs: the public JSON export (ToJson) of every generated record.

The export is hand-written C# (no reflection at run time, D19), so this script writes it from the record sources:
every `public T Name { get; init; }` of every `public sealed partial record` in the Runtime folder, in source order,
as camelCase keys. Run it after adding a field to a record, then run the tests (ExportTests checks that every public
property is exported and that the file is current).

Run: python scripts/gen-json-export.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUNTIME = ROOT / "Packages/com.m4bwav.universe-generator/Runtime"
OUT = RUNTIME / "Core/JsonExport.cs"

# The records with a ToJson method: what a caller holds after Generate or Universe.At.
TOP = ["Universe", "GalaxyCluster", "CosmicVoid", "Galaxy", "StarSystem", "Planet", "Moon", "Belt", "Station"]
# Lists generated when first read: left out unless children are asked for (each map entry carries the address).
LAZY = {("Galaxy", "Systems"), ("GalaxyCluster", "Galaxies"), ("CosmicVoid", "Systems")}
SKIP = {"GeneratorOptions", "StarName"}

RECORD = re.compile(r"^\s*public sealed (?:partial )?record (\w+)")
OTHER_TYPE = re.compile(r"^\s*(?:public|internal|private)\s+(?:static\s+|sealed\s+|abstract\s+|readonly\s+)*(?:partial\s+)?(?:class|struct|enum|record)\s+\w+")
PROPERTY = re.compile(r"^\s*public ([A-Za-z<>?,. ]+?) (\w+) \{ get; init; \}")
ENUM = re.compile(r"^\s*public enum (\w+)")


def scan():
    records, enums, files = {}, set(), {}
    for path in sorted(RUNTIME.rglob("*.cs")):
        if path == OUT:
            continue
        current = None
        for line in path.read_text(encoding="utf-8").splitlines():
            m = ENUM.match(line)
            if m:
                enums.add(m.group(1))
            m = RECORD.match(line)
            if m:
                current = m.group(1)
                records[current] = []
                files[current] = path
                continue
            if OTHER_TYPE.match(line):
                current = None
                continue
            m = PROPERTY.match(line)
            if m and current and current not in SKIP:
                records[current].append((m.group(1).replace(" ", ""), m.group(2)))
    for name in SKIP:
        records.pop(name, None)
    return records, enums, files


def camel(name):
    return name[0].lower() + name[1:]


def needs_children(name, records, seen=None):
    """True when the record, or a record below it, holds a lazy list."""
    seen = seen or set()
    if name in seen or name not in records:
        return False
    seen.add(name)
    for t, p in records[name]:
        if (name, p) in LAZY:
            return True
        inner = re.sub(r"^IReadOnlyList<(\w+)>$", r"\1", t).rstrip("?")
        if needs_children(inner, records, seen):
            return True
    return False


def value(t, expr, records, enums, record, prop):
    """C# statements writing expr of type t."""
    nullable = t.endswith("?")
    base = t.rstrip("?")
    m = re.match(r"^IReadOnlyList<(\w+)>$", base)
    if m:
        inner = m.group(1)
        body = value(inner, "item", records, enums, record, prop)
        lines = ["w.BeginArray();", f"foreach (var item in {expr})", "{"] + ["    " + b for b in body] + ["}", "w.EndArray();"]
        if (record, prop) in LAZY:
            return ["if (children)", "{"] + ["    " + l for l in lines] + ["}", "else", "{", "    w.Null();", "}"]
        return lines
    if base in ("int", "long"):
        write = f"w.Int({expr}{'.Value' if nullable else ''});"
    elif base == "double":
        write = f"Real(w, {expr}{'.Value' if nullable else ''});"
    elif base == "bool":
        write = f"w.Bool({expr}{'.Value' if nullable else ''});"
    elif base == "string":
        return [f"w.String({expr});"]
    elif base in enums:
        write = f"w.String({expr}{'.Value' if nullable else ''}.ToString());"
    elif base in records:
        write = f"Write(w, {expr}{'!' if nullable else ''}, children);"
    else:
        sys.exit(f"gen-json-export: no rule for {record}.{prop} of type {t}")
    if nullable:
        return [f"if ({expr} is null)", "{", "    w.Null();", "}", "else", "{", "    " + write, "}"]
    return [write]


def main():
    records, enums, files = scan()
    out = []
    out.append("// <auto-generated>")
    out.append("// Generated by scripts/gen-json-export.py from the records' init properties; do not edit by hand.")
    out.append("// Run the script after adding a field to a record (ExportTests fails until it is current).")
    out.append("// </auto-generated>")
    out.append("#nullable enable")
    out.append("namespace UniverseGeneration")
    out.append("{")
    for name in TOP:
        kids = needs_children(name, records)
        out.append(f"    public sealed partial record {name}")
        out.append("    {")
        out.append("        /// <summary>")
        out.append(f"        /// This {camel(name)} as JSON: every field, with a <c>schema</c> of <c>{'universe-generator/1'}</c> and a <c>type</c> of")
        out.append(f"        /// <c>{camel(name)}</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.")
        if kids:
            out.append("        /// Lists generated when first read (a galaxy's systems, a cluster's galaxies, a void's systems) are null unless")
            out.append("        /// <paramref name=\"children\"/> is true, which generates and writes them all; each map entry carries the address.")
        out.append("        /// </summary>")
        out.append("        /// <param name=\"indented\">Two-space indents and line feeds instead of one line.</param>")
        if kids:
            out.append("        /// <param name=\"children\">Write the lists generated when first read, generating every object below.</param>")
            out.append("        public string ToJson(bool indented = false, bool children = false)")
        else:
            out.append("        public string ToJson(bool indented = false)")
        out.append("        {")
        out.append("            var w = new JsonWriter(indented);")
        out.append(f"            JsonExport.Write(w, this, {'children' if kids else 'false'}, \"{camel(name)}\");")
        out.append("            return w.ToString();")
        out.append("        }")
        out.append("    }")
        out.append("")
    out.append("    /// <summary>The writers behind every <c>ToJson</c>: one per record, every init property in source order.</summary>")
    out.append("    internal static class JsonExport")
    out.append("    {")
    out.append("        /// <summary>The export format's name and version; a version changes only when a field changes meaning or goes.</summary>")
    out.append("        public const string Schema = \"universe-generator/1\";")
    out.append("")
    out.append("        // Each value with as many decimals as fit (at most 9), decided by comparison alone, so the same on every runtime.")
    out.append("        private static void Real(JsonWriter w, double v)")
    out.append("        {")
    out.append("            var a = v < 0 ? -v : v;")
    out.append("            var decimals = 9;")
    out.append("            var limit = 9007199254740992.0 / 1e9;")
    out.append("            while (decimals > 0 && a >= limit)")
    out.append("            {")
    out.append("                decimals--;")
    out.append("                limit *= 10;")
    out.append("            }")
    out.append("")
    out.append("            w.Number(v, decimals);")
    out.append("        }")
    for name in sorted(records):
        props = records[name]
        out.append("")
        if name in TOP:
            out.append(f"        public static void Write(JsonWriter w, {name} v, bool children, string type)")
            out.append("        {")
            out.append("            w.BeginObject().Name(\"schema\").String(Schema).Name(\"type\").String(type);")
            out.append("            Fields(w, v, children);")
            out.append("            w.EndObject();")
            out.append("        }")
            out.append("")
        out.append(f"        public static void Write(JsonWriter w, {name} v, bool children)")
        out.append("        {")
        out.append("            w.BeginObject();")
        out.append("            Fields(w, v, children);")
        out.append("            w.EndObject();")
        out.append("        }")
        out.append("")
        used = any("children" in l for t, p in props for l in value(t, "v." + p, records, enums, name, p))
        out.append(f"        private static void Fields(JsonWriter w, {name} v, bool children)")
        out.append("        {")
        if not used:
            out.append("            _ = children;")
        for t, p in props:
            out.append(f"            w.Name(\"{camel(p)}\");")
            for l in value(t, "v." + p, records, enums, name, p):
                out.append("            " + l)
        out.append("        }")
    out.append("    }")
    out.append("}")
    text = "\n".join(out) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit("Runtime/Core/JsonExport.cs is out of date: run python scripts/gen-json-export.py")
        print("JsonExport.cs is current")
        return
    OUT.write_bytes(text.encode("utf-8"))
    # Make the TOP records partial so the generated ToJson methods join them.
    for name in TOP:
        path = files[name]
        src = path.read_bytes().decode("utf-8")
        src2 = re.sub(rf"public sealed record {name}\b", f"public sealed partial record {name}", src)
        if src2 != src:
            path.write_bytes(src2.encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(records)} records, {sum(len(p) for p in records.values())} fields")


if __name__ == "__main__":
    main()
