// <auto-generated>
// Generated by scripts/gen-json-export.py from the records' init properties; do not edit by hand.
// Run the script after adding a field to a record (ExportTests fails until it is current).
// </auto-generated>
#nullable enable
namespace UniverseGeneration
{
    public sealed partial record Universe
    {
        /// <summary>
        /// This universe as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>universe</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// Lists generated when first read (a galaxy's systems, a cluster's galaxies, a void's systems) are null unless
        /// <paramref name="children"/> is true, which generates and writes them all; each map entry carries the address.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        /// <param name="children">Write the lists generated when first read, generating every object below.</param>
        public string ToJson(bool indented = false, bool children = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, children, "universe");
            return w.ToString();
        }
    }

    public sealed partial record GalaxyCluster
    {
        /// <summary>
        /// This galaxyCluster as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>galaxyCluster</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// Lists generated when first read (a galaxy's systems, a cluster's galaxies, a void's systems) are null unless
        /// <paramref name="children"/> is true, which generates and writes them all; each map entry carries the address.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        /// <param name="children">Write the lists generated when first read, generating every object below.</param>
        public string ToJson(bool indented = false, bool children = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, children, "galaxyCluster");
            return w.ToString();
        }
    }

    public sealed partial record CosmicVoid
    {
        /// <summary>
        /// This cosmicVoid as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>cosmicVoid</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// Lists generated when first read (a galaxy's systems, a cluster's galaxies, a void's systems) are null unless
        /// <paramref name="children"/> is true, which generates and writes them all; each map entry carries the address.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        /// <param name="children">Write the lists generated when first read, generating every object below.</param>
        public string ToJson(bool indented = false, bool children = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, children, "cosmicVoid");
            return w.ToString();
        }
    }

    public sealed partial record Galaxy
    {
        /// <summary>
        /// This galaxy as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>galaxy</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// Lists generated when first read (a galaxy's systems, a cluster's galaxies, a void's systems) are null unless
        /// <paramref name="children"/> is true, which generates and writes them all; each map entry carries the address.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        /// <param name="children">Write the lists generated when first read, generating every object below.</param>
        public string ToJson(bool indented = false, bool children = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, children, "galaxy");
            return w.ToString();
        }
    }

    public sealed partial record StarSystem
    {
        /// <summary>
        /// This starSystem as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>starSystem</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        public string ToJson(bool indented = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, false, "starSystem");
            return w.ToString();
        }
    }

    public sealed partial record Planet
    {
        /// <summary>
        /// This planet as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>planet</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        public string ToJson(bool indented = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, false, "planet");
            return w.ToString();
        }
    }

    public sealed partial record Moon
    {
        /// <summary>
        /// This moon as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>moon</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        public string ToJson(bool indented = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, false, "moon");
            return w.ToString();
        }
    }

    public sealed partial record Belt
    {
        /// <summary>
        /// This belt as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>belt</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        public string ToJson(bool indented = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, false, "belt");
            return w.ToString();
        }
    }

    public sealed partial record Station
    {
        /// <summary>
        /// This station as JSON: every field, with a <c>schema</c> of <c>universe-generator/1</c> and a <c>type</c> of
        /// <c>station</c> first; enum values as their names, numbers rounded as stored, the same text on every runtime.
        /// </summary>
        /// <param name="indented">Two-space indents and line feeds instead of one line.</param>
        public string ToJson(bool indented = false)
        {
            var w = new JsonWriter(indented);
            JsonExport.Write(w, this, false, "station");
            return w.ToString();
        }
    }

    /// <summary>The writers behind every <c>ToJson</c>: one per record, every init property in source order.</summary>
    internal static class JsonExport
    {
        /// <summary>The export format's name and version; a version changes only when a field changes meaning or goes.</summary>
        public const string Schema = "universe-generator/1";

        // Each value with as many decimals as fit (at most 9), decided by comparison alone, so the same on every runtime.
        private static void Real(JsonWriter w, double v)
        {
            var a = v < 0 ? -v : v;
            var decimals = 9;
            var limit = 9007199254740992.0 / 1e9;
            while (decimals > 0 && a >= limit)
            {
                decimals--;
                limit *= 10;
            }

            w.Number(v, decimals);
        }

        public static void Write(JsonWriter w, Atmosphere v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Atmosphere v, bool children)
        {
            _ = children;
            w.Name("class");
            w.String(v.Class.ToString());
            w.Name("pressure");
            if (v.Pressure is null)
            {
                w.Null();
            }
            else
            {
                Real(w, v.Pressure.Value);
            }
            w.Name("gases");
            w.BeginArray();
            foreach (var item in v.Gases)
            {
                w.String(item.ToString());
            }
            w.EndArray();
            w.Name("lightestGasKept");
            Real(w, v.LightestGasKept);
            w.Name("breathable");
            w.Bool(v.Breathable);
            w.Name("why");
            w.String(v.Why);
        }

        public static void Write(JsonWriter w, Beacon v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Beacon v, bool children)
        {
            _ = children;
            w.Name("system");
            w.Int(v.System);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("name");
            w.String(v.Name);
            w.Name("text");
            w.String(v.Text);
        }

        public static void Write(JsonWriter w, Belt v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Belt v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Belt v, bool children)
        {
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("inner");
            Real(w, v.Inner);
            w.Name("outer");
            Real(w, v.Outer);
            w.Name("address");
            w.String(v.Address);
            w.Name("index");
            w.Int(v.Index);
            w.Name("name");
            w.String(v.Name);
            w.Name("composition");
            Write(w, v.Composition, children);
            w.Name("mass");
            Real(w, v.Mass);
            w.Name("largestBody");
            Real(w, v.LargestBody);
            w.Name("temperature");
            Real(w, v.Temperature);
            w.Name("resources");
            Write(w, v.Resources, children);
            w.Name("summary");
            w.String(v.Summary);
        }

        public static void Write(JsonWriter w, BeltComposition v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, BeltComposition v, bool children)
        {
            _ = children;
            w.Name("silicate");
            w.Int(v.Silicate);
            w.Name("carbonaceous");
            w.Int(v.Carbonaceous);
            w.Name("metal");
            w.Int(v.Metal);
            w.Name("ice");
            w.Int(v.Ice);
        }

        public static void Write(JsonWriter w, BiomeShare v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, BiomeShare v, bool children)
        {
            _ = children;
            w.Name("biome");
            w.String(v.Biome.ToString());
            w.Name("share");
            Real(w, v.Share);
        }

        public static void Write(JsonWriter w, ClimateBand v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, ClimateBand v, bool children)
        {
            _ = children;
            w.Name("from");
            w.Int(v.From);
            w.Name("to");
            w.Int(v.To);
            w.Name("share");
            Real(w, v.Share);
            w.Name("temperature");
            Real(w, v.Temperature);
            w.Name("biome");
            w.String(v.Biome.ToString());
        }

        public static void Write(JsonWriter w, ClusterEntry v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, ClusterEntry v, bool children)
        {
            _ = children;
            w.Name("index");
            w.Int(v.Index);
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("type");
            w.String(v.Type);
            w.Name("shape");
            w.String(v.Shape.ToString());
            w.Name("role");
            w.String(v.Role.ToString());
            w.Name("host");
            w.Int(v.Host);
            w.Name("x");
            Real(w, v.X);
            w.Name("y");
            Real(w, v.Y);
            w.Name("size");
            Real(w, v.Size);
            w.Name("systems");
            w.Int(v.Systems);
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("richness");
            w.String(v.Richness.ToString());
            w.Name("coreActivity");
            w.String(v.CoreActivity.ToString());
        }

        public static void Write(JsonWriter w, ClusterLink v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, ClusterLink v, bool children)
        {
            _ = children;
            w.Name("a");
            w.Int(v.A);
            w.Name("b");
            w.Int(v.B);
            w.Name("tier");
            w.String(v.Tier.ToString());
            w.Name("length");
            Real(w, v.Length);
        }

        public static void Write(JsonWriter w, Companion v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Companion v, bool children)
        {
            w.Name("star");
            Write(w, v.Star, children);
            w.Name("orbit");
            w.String(v.Orbit.ToString());
            w.Name("separation");
            Real(w, v.Separation);
        }

        public static void Write(JsonWriter w, CosmicVoid v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, CosmicVoid v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, CosmicVoid v, bool children)
        {
            w.Name("index");
            w.Int(v.Index);
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("x");
            Real(w, v.X);
            w.Name("y");
            Real(w, v.Y);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("systems");
            if (children)
            {
                w.BeginArray();
                foreach (var item in v.Systems)
                {
                    Write(w, item, children);
                }
                w.EndArray();
            }
            else
            {
                w.Null();
            }
        }

        public static void Write(JsonWriter w, Faction v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Faction v, bool children)
        {
            _ = children;
            w.Name("index");
            w.Int(v.Index);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("capital");
            w.Int(v.Capital);
            w.Name("systems");
            w.Int(v.Systems);
            w.Name("description");
            w.String(v.Description);
        }

        public static void Write(JsonWriter w, Filament v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Filament v, bool children)
        {
            _ = children;
            w.Name("a");
            w.Int(v.A);
            w.Name("b");
            w.Int(v.B);
            w.Name("length");
            Real(w, v.Length);
            w.Name("galaxyA");
            w.Int(v.GalaxyA);
            w.Name("galaxyB");
            w.Int(v.GalaxyB);
        }

        public static void Write(JsonWriter w, Galaxy v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Galaxy v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Galaxy v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("type");
            w.String(v.Type);
            w.Name("descriptor");
            w.String(v.Descriptor);
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("richness");
            w.String(v.Richness.ToString());
            w.Name("coreActivity");
            w.String(v.CoreActivity.ToString());
            w.Name("coreHazardRadius");
            Real(w, v.CoreHazardRadius);
            w.Name("gates");
            w.BeginArray();
            foreach (var item in v.Gates)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("landmark");
            if (v.Landmark is null)
            {
                w.Null();
            }
            else
            {
                Write(w, v.Landmark!, children);
            }
            w.Name("shape");
            w.String(v.Shape.ToString());
            w.Name("arms");
            w.Int(v.Arms);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("core");
            w.Int(v.Core);
            w.Name("map");
            w.BeginArray();
            foreach (var item in v.Map)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("lanes");
            w.BeginArray();
            foreach (var item in v.Lanes)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("regions");
            w.BeginArray();
            foreach (var item in v.Regions)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("systems");
            if (children)
            {
                w.BeginArray();
                foreach (var item in v.Systems)
                {
                    Write(w, item, children);
                }
                w.EndArray();
            }
            else
            {
                w.Null();
            }
            w.Name("factions");
            w.BeginArray();
            foreach (var item in v.Factions)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("pointsOfInterest");
            w.BeginArray();
            foreach (var item in v.PointsOfInterest)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("hazards");
            w.BeginArray();
            foreach (var item in v.Hazards)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("monuments");
            w.BeginArray();
            foreach (var item in v.Monuments)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("beacons");
            w.BeginArray();
            foreach (var item in v.Beacons)
            {
                Write(w, item, children);
            }
            w.EndArray();
        }

        public static void Write(JsonWriter w, GalaxyCluster v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, GalaxyCluster v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, GalaxyCluster v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("map");
            w.BeginArray();
            foreach (var item in v.Map)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("links");
            w.BeginArray();
            foreach (var item in v.Links)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("galaxies");
            if (children)
            {
                w.BeginArray();
                foreach (var item in v.Galaxies)
                {
                    Write(w, item, children);
                }
                w.EndArray();
            }
            else
            {
                w.Null();
            }
        }

        public static void Write(JsonWriter w, GalaxyGate v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, GalaxyGate v, bool children)
        {
            _ = children;
            w.Name("galaxy");
            w.Int(v.Galaxy);
            w.Name("name");
            w.String(v.Name);
            w.Name("tier");
            w.String(v.Tier.ToString());
            w.Name("system");
            w.Int(v.System);
            w.Name("cluster");
            w.Int(v.Cluster);
        }

        public static void Write(JsonWriter w, GalaxyHazard v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, GalaxyHazard v, bool children)
        {
            _ = children;
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("name");
            w.String(v.Name);
            w.Name("x");
            Real(w, v.X);
            w.Name("y");
            Real(w, v.Y);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("systems");
            w.BeginArray();
            foreach (var item in v.Systems)
            {
                w.Int(item);
            }
            w.EndArray();
            w.Name("effect");
            w.String(v.Effect);
        }

        public static void Write(JsonWriter w, GalaxyRegion v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, GalaxyRegion v, bool children)
        {
            _ = children;
            w.Name("index");
            w.Int(v.Index);
            w.Name("name");
            w.String(v.Name);
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("theme");
            w.String(v.Theme);
            w.Name("centre");
            w.Int(v.Centre);
        }

        public static void Write(JsonWriter w, Landmark v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Landmark v, bool children)
        {
            _ = children;
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("planet");
            if (v.Planet is null)
            {
                w.Null();
            }
            else
            {
                w.Int(v.Planet.Value);
            }
            w.Name("outlier");
            w.Bool(v.Outlier);
            w.Name("text");
            w.String(v.Text);
        }

        public static void Write(JsonWriter w, Lane v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Lane v, bool children)
        {
            _ = children;
            w.Name("a");
            w.Int(v.A);
            w.Name("b");
            w.Int(v.B);
            w.Name("bridge");
            w.Bool(v.Bridge);
        }

        public static void Write(JsonWriter w, MapEntry v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, MapEntry v, bool children)
        {
            _ = children;
            w.Name("index");
            w.Int(v.Index);
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("x");
            Real(w, v.X);
            w.Name("y");
            Real(w, v.Y);
            w.Name("starClass");
            w.String(v.StarClass.ToString());
            w.Name("region");
            w.Int(v.Region);
            w.Name("hops");
            w.Int(v.Hops);
            w.Name("danger");
            w.Int(v.Danger);
            w.Name("chokepoint");
            w.Bool(v.Chokepoint);
            w.Name("faction");
            if (v.Faction is null)
            {
                w.Null();
            }
            else
            {
                w.Int(v.Faction.Value);
            }
            w.Name("contested");
            w.Bool(v.Contested);
        }

        public static void Write(JsonWriter w, Monument v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Monument v, bool children)
        {
            _ = children;
            w.Name("region");
            w.Int(v.Region);
            w.Name("system");
            w.Int(v.System);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("name");
            w.String(v.Name);
            w.Name("text");
            w.String(v.Text);
        }

        public static void Write(JsonWriter w, Moon v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Moon v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Moon v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("index");
            w.Int(v.Index);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("orbit");
            Real(w, v.Orbit);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("descriptor");
            w.String(v.Descriptor);
            w.Name("distance");
            Real(w, v.Distance);
            w.Name("period");
            Real(w, v.Period);
            w.Name("composition");
            w.String(v.Composition.ToString());
            w.Name("density");
            Real(w, v.Density);
            w.Name("mass");
            Real(w, v.Mass);
            w.Name("gravity");
            Real(w, v.Gravity);
            w.Name("escapeVelocity");
            Real(w, v.EscapeVelocity);
            w.Name("insolation");
            Real(w, v.Insolation);
            w.Name("albedo");
            Real(w, v.Albedo);
            w.Name("tidalHeating");
            Real(w, v.TidalHeating);
            w.Name("temperature");
            Real(w, v.Temperature);
            w.Name("dayTemperature");
            Real(w, v.DayTemperature);
            w.Name("nightTemperature");
            Real(w, v.NightTemperature);
            w.Name("atmosphere");
            Write(w, v.Atmosphere, children);
            w.Name("water");
            Real(w, v.Water);
            w.Name("ice");
            Real(w, v.Ice);
            w.Name("subsurfaceOcean");
            w.Bool(v.SubsurfaceOcean);
            w.Name("rotation");
            Real(w, v.Rotation);
            w.Name("tilt");
            Real(w, v.Tilt);
            w.Name("bands");
            w.BeginArray();
            foreach (var item in v.Bands)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("biomes");
            w.BeginArray();
            foreach (var item in v.Biomes)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("life");
            w.String(v.Life.ToString());
            w.Name("flora");
            w.Int(v.Flora);
            w.Name("fauna");
            w.Int(v.Fauna);
            w.Name("traits");
            w.BeginArray();
            foreach (var item in v.Traits)
            {
                w.String(item);
            }
            w.EndArray();
            w.Name("anomaly");
            w.String(v.Anomaly);
            w.Name("resources");
            Write(w, v.Resources, children);
            w.Name("hazard");
            w.Int(v.Hazard);
            w.Name("hazards");
            w.BeginArray();
            foreach (var item in v.Hazards)
            {
                w.String(item);
            }
            w.EndArray();
            w.Name("similarity");
            Real(w, v.Similarity);
            w.Name("habitability");
            w.String(v.Habitability.ToString());
            w.Name("summary");
            w.String(v.Summary);
        }

        public static void Write(JsonWriter w, Planet v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Planet v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Planet v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("index");
            w.Int(v.Index);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("zone");
            w.String(v.Zone.ToString());
            w.Name("orbit");
            Real(w, v.Orbit);
            w.Name("period");
            Real(w, v.Period);
            w.Name("mass");
            Real(w, v.Mass);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("rings");
            w.Bool(v.Rings);
            w.Name("moons");
            w.BeginArray();
            foreach (var item in v.Moons)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("descriptor");
            w.String(v.Descriptor);
            w.Name("composition");
            w.String(v.Composition.ToString());
            w.Name("gravity");
            Real(w, v.Gravity);
            w.Name("escapeVelocity");
            Real(w, v.EscapeVelocity);
            w.Name("density");
            Real(w, v.Density);
            w.Name("insolation");
            Real(w, v.Insolation);
            w.Name("albedo");
            Real(w, v.Albedo);
            w.Name("temperature");
            Real(w, v.Temperature);
            w.Name("dayTemperature");
            Real(w, v.DayTemperature);
            w.Name("nightTemperature");
            Real(w, v.NightTemperature);
            w.Name("atmosphere");
            Write(w, v.Atmosphere, children);
            w.Name("water");
            Real(w, v.Water);
            w.Name("ice");
            Real(w, v.Ice);
            w.Name("rotation");
            Real(w, v.Rotation);
            w.Name("spin");
            w.String(v.Spin.ToString());
            w.Name("tilt");
            Real(w, v.Tilt);
            w.Name("bands");
            w.BeginArray();
            foreach (var item in v.Bands)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("biomes");
            w.BeginArray();
            foreach (var item in v.Biomes)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("life");
            w.String(v.Life.ToString());
            w.Name("flora");
            w.Int(v.Flora);
            w.Name("fauna");
            w.Int(v.Fauna);
            w.Name("traits");
            w.BeginArray();
            foreach (var item in v.Traits)
            {
                w.String(item);
            }
            w.EndArray();
            w.Name("anomaly");
            w.String(v.Anomaly);
            w.Name("resources");
            Write(w, v.Resources, children);
            w.Name("hazard");
            w.Int(v.Hazard);
            w.Name("hazards");
            w.BeginArray();
            foreach (var item in v.Hazards)
            {
                w.String(item);
            }
            w.EndArray();
            w.Name("similarity");
            Real(w, v.Similarity);
            w.Name("habitability");
            w.String(v.Habitability.ToString());
            w.Name("summary");
            w.String(v.Summary);
        }

        public static void Write(JsonWriter w, PointOfInterest v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, PointOfInterest v, bool children)
        {
            _ = children;
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("system");
            w.Int(v.System);
            w.Name("name");
            w.String(v.Name);
            w.Name("text");
            w.String(v.Text);
            w.Name("chainStep");
            w.Int(v.ChainStep);
            w.Name("chainLength");
            w.Int(v.ChainLength);
        }

        public static void Write(JsonWriter w, ResourceGrades v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, ResourceGrades v, bool children)
        {
            _ = children;
            w.Name("metals");
            w.Int(v.Metals);
            w.Name("rareElements");
            w.Int(v.RareElements);
            w.Name("ices");
            w.Int(v.Ices);
            w.Name("gases");
            w.Int(v.Gases);
            w.Name("organics");
            w.Int(v.Organics);
        }

        public static void Write(JsonWriter w, SkyLandmark v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, SkyLandmark v, bool children)
        {
            _ = children;
            w.Name("name");
            w.String(v.Name);
            w.Name("address");
            w.String(v.Address);
            w.Name("bearing");
            w.Int(v.Bearing);
            w.Name("lightYears");
            w.Int(v.LightYears);
        }

        public static void Write(JsonWriter w, Species v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Species v, bool children)
        {
            _ = children;
            w.Name("name");
            w.String(v.Name);
            w.Name("minTemperature");
            Real(w, v.MinTemperature);
            w.Name("maxTemperature");
            Real(w, v.MaxTemperature);
            w.Name("minGravity");
            Real(w, v.MinGravity);
            w.Name("maxGravity");
            Real(w, v.MaxGravity);
            w.Name("minPressure");
            Real(w, v.MinPressure);
            w.Name("maxPressure");
            Real(w, v.MaxPressure);
            w.Name("breathesOxygen");
            w.Bool(v.BreathesOxygen);
        }

        public static void Write(JsonWriter w, Star v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Star v, bool children)
        {
            _ = children;
            w.Name("class");
            w.String(v.Class.ToString());
            w.Name("spectralType");
            w.String(v.SpectralType);
            w.Name("mass");
            Real(w, v.Mass);
            w.Name("luminosity");
            Real(w, v.Luminosity);
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("temperature");
            Real(w, v.Temperature);
            w.Name("colour");
            w.String(v.Colour);
            w.Name("description");
            w.String(v.Description);
        }

        public static void Write(JsonWriter w, StarSystem v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, StarSystem v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, StarSystem v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("star");
            Write(w, v.Star, children);
            w.Name("companion");
            if (v.Companion is null)
            {
                w.Null();
            }
            else
            {
                Write(w, v.Companion!, children);
            }
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("danger");
            w.Int(v.Danger);
            w.Name("habitableZoneInner");
            Real(w, v.HabitableZoneInner);
            w.Name("habitableZoneOuter");
            Real(w, v.HabitableZoneOuter);
            w.Name("frostLine");
            Real(w, v.FrostLine);
            w.Name("planets");
            w.BeginArray();
            foreach (var item in v.Planets)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("belts");
            w.BeginArray();
            foreach (var item in v.Belts)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("stations");
            w.BeginArray();
            foreach (var item in v.Stations)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("landmarks");
            w.BeginArray();
            foreach (var item in v.Landmarks)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("tags");
            w.BeginArray();
            foreach (var item in v.Tags)
            {
                w.String(item);
            }
            w.EndArray();
            w.Name("descriptor");
            w.String(v.Descriptor);
        }

        public static void Write(JsonWriter w, Station v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Station v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Station v, bool children)
        {
            _ = children;
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("planet");
            if (v.Planet is null)
            {
                w.Null();
            }
            else
            {
                w.Int(v.Planet.Value);
            }
        }

        public static void Write(JsonWriter w, Universe v, bool children, string type)
        {
            w.BeginObject().Name("schema").String(Schema).Name("type").String(type);
            Fields(w, v, children);
            w.EndObject();
        }

        public static void Write(JsonWriter w, Universe v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, Universe v, bool children)
        {
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("age");
            w.String(v.Age.ToString());
            w.Name("radius");
            Real(w, v.Radius);
            w.Name("nodes");
            w.BeginArray();
            foreach (var item in v.Nodes)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("filaments");
            w.BeginArray();
            foreach (var item in v.Filaments)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("voids");
            w.BeginArray();
            foreach (var item in v.Voids)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("landmarks");
            w.BeginArray();
            foreach (var item in v.Landmarks)
            {
                Write(w, item, children);
            }
            w.EndArray();
            w.Name("merger");
            Write(w, v.Merger, children);
            w.Name("clusters");
            w.BeginArray();
            foreach (var item in v.Clusters)
            {
                Write(w, item, children);
            }
            w.EndArray();
        }

        public static void Write(JsonWriter w, UniverseLandmark v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, UniverseLandmark v, bool children)
        {
            _ = children;
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("name");
            w.String(v.Name);
            w.Name("address");
            w.String(v.Address);
        }

        public static void Write(JsonWriter w, UniverseMerger v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, UniverseMerger v, bool children)
        {
            _ = children;
            w.Name("name");
            w.String(v.Name);
            w.Name("cluster");
            w.Int(v.Cluster);
            w.Name("galaxyA");
            w.String(v.GalaxyA);
            w.Name("galaxyB");
            w.String(v.GalaxyB);
            w.Name("hook");
            w.String(v.Hook);
        }

        public static void Write(JsonWriter w, UniverseNode v, bool children)
        {
            w.BeginObject();
            Fields(w, v, children);
            w.EndObject();
        }

        private static void Fields(JsonWriter w, UniverseNode v, bool children)
        {
            _ = children;
            w.Name("index");
            w.Int(v.Index);
            w.Name("address");
            w.String(v.Address);
            w.Name("name");
            w.String(v.Name);
            w.Name("kind");
            w.String(v.Kind.ToString());
            w.Name("role");
            w.String(v.Role.ToString());
            w.Name("x");
            Real(w, v.X);
            w.Name("y");
            Real(w, v.Y);
            w.Name("galaxies");
            w.Int(v.Galaxies);
        }
    }
}
